server {
    listen 0.0.0.0:80;
    listen 0.0.0.0:8080;
    server_name _;

    location / {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:8000;
    }

    location /api/ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:8000;
        fastcgi_param SCRIPT_NAME /api;
        fastcgi_param PATH_INFO $fastcgi_script_name;
    }
} 